// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type FooterDocumentDataSlicesSlice = never;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Title field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Privacy Link field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.privacy_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  privacy_link: prismic.LinkField;

  /**
   * Cookie Link field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.cookie_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cookie_link: prismic.LinkField;

  /**
   * Slice Zone field in *Footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FooterDocumentDataSlicesSlice>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | VideosSlice
  | ServicesTeamSlice
  | HeaderSlice;

/**
 * Content for homepage documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
}

/**
 * homepage document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = FooterDocument | PageDocument;

/**
 * Primary content in *Header → Primary*
 */
export interface HeaderSliceDefaultPrimary {
  /**
   * Logo field in *Header → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Website title field in *Header → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.primary.website_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  website_title: prismic.KeyTextField;

  /**
   * Logo dark mode field in *Header → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.primary.logo_dark_mode
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_dark_mode: prismic.ImageField<never>;
}

/**
 * Default variation for Header Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Header*
 */
type HeaderSliceVariation = HeaderSliceDefault;

/**
 * Header Shared Slice
 *
 * - **API ID**: `header`
 * - **Description**: Header
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSlice = prismic.SharedSlice<"header", HeaderSliceVariation>;

/**
 * Primary content in *ServicesTeam → Primary*
 */
export interface ServicesTeamSliceDefaultPrimary {
  /**
   * Title text field in *ServicesTeam → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_team.primary.title_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_text: prismic.KeyTextField;

  /**
   * Description field in *ServicesTeam → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_team.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Second title text  field in *ServicesTeam → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_team.primary.second_title_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  second_title_text: prismic.KeyTextField;

  /**
   * Secondary description field in *ServicesTeam → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_team.primary.secondary_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  secondary_description: prismic.RichTextField;

  /**
   * Button text field in *ServicesTeam → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_team.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button description field in *ServicesTeam → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_team.primary.button_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  button_description: prismic.RichTextField;
}

/**
 * Default variation for ServicesTeam Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesTeamSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesTeamSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServicesTeam*
 */
type ServicesTeamSliceVariation = ServicesTeamSliceDefault;

/**
 * ServicesTeam Shared Slice
 *
 * - **API ID**: `services_team`
 * - **Description**: ServicesTeam
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesTeamSlice = prismic.SharedSlice<
  "services_team",
  ServicesTeamSliceVariation
>;

/**
 * Primary content in *ImagesAndVideos → Items*
 */
export interface VideosSliceDefaultItem {
  /**
   * Image/Video field in *ImagesAndVideos → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: videos.items[].video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkToMediaField;
}

/**
 * Default variation for ImagesAndVideos Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<VideosSliceDefaultItem>
>;

/**
 * Slice variation for *ImagesAndVideos*
 */
type VideosSliceVariation = VideosSliceDefault;

/**
 * ImagesAndVideos Shared Slice
 *
 * - **API ID**: `videos`
 * - **Description**: Videos
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideosSlice = prismic.SharedSlice<"videos", VideosSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      HeaderSlice,
      HeaderSliceDefaultPrimary,
      HeaderSliceVariation,
      HeaderSliceDefault,
      ServicesTeamSlice,
      ServicesTeamSliceDefaultPrimary,
      ServicesTeamSliceVariation,
      ServicesTeamSliceDefault,
      VideosSlice,
      VideosSliceDefaultItem,
      VideosSliceVariation,
      VideosSliceDefault,
    };
  }
}
