// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  header: dynamic(() => import("./Header")),
  services_team: dynamic(() => import("./ServicesTeam")),
  videos: dynamic(() => import("./ImagesAndVideos")),
};
