// Code generated by Slice Machine. DO NOT EDIT.

import CallToAction from './CallToAction';
import FindUsOn from './FindUsOn';
import Team from './Team';

export {
	CallToAction,
	FindUsOn,
	Team,
};

export const components = {
	call_to_action: CallToAction,
	find_us_on: FindUsOn,
	hero: Team,
};
