// Code generated by Slice Machine. DO NOT EDIT.

import CallToAction from "./CallToAction";
import FindUsOn from "./FindUsOn";
import Team from "./Team";
import ServicesTeam from "./ServicesTeam";
import Header from "./Header";
import Images from "./Images";

export { CallToAction, FindUsOn, Team, ServicesTeam, Header, Images };

export const components = {
  call_to_action: CallToAction,
  find_us_on: FindUsOn,
  hero: Team,
  services_team: ServicesTeam,
  header: Header,
  images: Images,
};
